from enum import StrEnum

class ConversationState(StrEnum):
    # Initial
    START = "START"
    
    # Booking Flow
    SELECT_SERVICE = "SELECT_SERVICE"
    SELECT_DATE = "SELECT_DATE"
    SELECT_TIME = "SELECT_TIME"
    
    PROVIDE_NAME = "PROVIDE_NAME"
    PROVIDE_STREET = "PROVIDE_STREET"
    PROVIDE_NUMBER = "PROVIDE_NUMBER"
    PROVIDE_NEIGHBORHOOD = "PROVIDE_NEIGHBORHOOD"
    PROVIDE_CITY = "PROVIDE_CITY"
    PROVIDE_ZIP = "PROVIDE_ZIP"
    
    # Final
    CONFIRMATION = "CONFIRMATION"
    FINISHED = "FINISHED"
